export default () => ({

    // Armors

    // Leather Set

    leatherHelmet: {
        label: 'Leather Helmet',
        name: 'leatherHelmet',
        type: 'helmet',
        set: 'leather',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 2,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    leatherChestplate: {
        label: 'Leather Chestplate',
        name: 'leatherChestplate',
        type: 'chestplate',
        set: 'leather',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 2,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    leatherLeggings: {
        label: 'Leather Leggings',
        name: 'leatherLeggings',
        type: 'leggings',
        set: 'leather',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 2,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    leatherBoots: {
        label: 'Leather Boots',
        name: 'leatherBoots',
        type: 'boots',
        set: 'leather',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 2,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Chainmail Armor

    chainmailHelmet: {
        label: 'Chainmail Helmet',
        name: 'chainmailHelmet',
        type: 'helmet',
        set: 'chainmail',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 2,
        defenseBonus: 1,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    chainmailChestplate: {
        label: 'Chainmail Chestplate',
        name: 'chainmailChestplate',
        type: 'chestplate',
        set: 'chainmail',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 2,
        defenseBonus: 1,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    chainmailLeggings: {
        label: 'Chainmail Leggings',
        name: 'chainmailLeggings',
        type: 'leggings',
        set: 'chainmail',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 2,
        defenseBonus: 1,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    chainmailBoots: {
        label: 'Chainmail Boots',
        name: 'chainmailBoots',
        type: 'boots',
        set: 'chainmail',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 2,
        defenseBonus: 1,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Iron Armor

    ironHelmet: {
        label: 'Iron Helmet',
        name: 'ironHelmet',
        type: 'helmet',
        set: 'iron',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 2,
        defenseBonus: 1,
        strengthBonus: 1,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    ironChestplate: {
        label: 'Iron Chestplate',
        name: 'ironChestplate',
        type: 'chestplate',
        set: 'iron',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 2,
        defenseBonus: 1,
        strengthBonus: 1,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    ironLeggings: {
        label: 'Iron Leggings',
        name: 'ironLeggings',
        type: 'leggings',
        set: 'iron',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 2,
        defenseBonus: 1,
        strengthBonus: 1,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    ironBoots: {
        label: 'Iron Boots',
        name: 'ironBoots',
        type: 'boots',
        set: 'iron',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 2,
        defenseBonus: 1,
        strengthBonus: 1,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Diamond Armor

    diamondHelmet: {
        label: 'Diamond Helmet',
        name: 'diamondHelmet',
        type: 'helmet',
        set: 'diamond',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 3,
        defenseBonus: 1,
        strengthBonus: 2,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    diamondChestplate: {
        label: 'Diamond Chestplate',
        name: 'diamondChestplate',
        type: 'chestplate',
        set: 'diamond',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 3,
        defenseBonus: 1,
        strengthBonus: 2,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    diamondLeggings: {
        label: 'Diamond Leggings',
        name: 'diamondLeggings',
        type: 'leggings',
        set: 'diamond',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 3,
        defenseBonus: 1,
        strengthBonus: 2,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    diamondBoots: {
        label: 'Diamond Boots',
        name: 'diamondBoots',
        type: 'boots',
        set: 'diamond',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 3,
        defenseBonus: 1,
        strengthBonus: 2,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Reinforced Diamond Armor

    reinforcedDiamondHelmet: {
        label: 'Reinforced Diamond Helmet',
        name: 'reinforcedDiamondHelmet',
        type: 'helmet',
        set: 'reinforcedDiamond',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 5,
        defenseBonus: 2,
        strengthBonus: 3,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    reinforcedDiamondChestplate: {
        label: 'Reinforced Diamond Chestplate',
        name: 'reinforcedDiamondChestplate',
        type: 'chestplate',
        set: 'reinforcedDiamond',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 5,
        defenseBonus: 2,
        strengthBonus: 3,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    reinforcedDiamondLeggings: {
        label: 'Reinforced Diamond Leggings',
        name: 'reinforcedDiamondLeggings',
        type: 'leggings',
        set: 'reinforcedDiamond',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 5,
        defenseBonus: 2,
        strengthBonus: 3,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    reinforcedDiamondBoots: {
        label: 'Reinforced Diamond Boots',
        name: 'reinforcedDiamondBoots',
        type: 'boots',
        set: 'reinforcedDiamond',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 5,
        defenseBonus: 2,
        strengthBonus: 3,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Special Armors

    // Worm Slayer

    wormSkull: {
        label: 'Worm Skull',
        name: 'wormSkull',
        type: 'helmet',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 10,
        defenseBonus: 2,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 3,
    },

    // Spider Slayer

    venomousHelmet: {
        label: 'Venomous Helmet',
        name: 'venomousHelmet',
        type: 'helmet',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 10,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    voraciousHelmet: {
        label: 'Voracious Helmet',
        name: 'voraciousHelmet',
        type: 'helmet',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 3,
        defenseBonus: 3,
        strengthBonus: 15,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Wolf Slayer

    packShield: {
        label: 'Pack Shield',
        name: 'packShield',
        specialEffect: 'ignoresEnemyDefense',
        effectLore: "Ignores the enemy's defense",
        type: 'accessory',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Werewolf Armor

    werewolfHelmet: {
        label: 'Werewolf Helmet',
        name: 'werewolfHelmet',
        type: 'helmet',
        set: 'werewolf',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 10,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    werewolfChestplate: {
        label: 'Werewolf Chestplate',
        name: 'werewolfChestplate',
        type: 'chestplate',
        set: 'werewolf',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 10,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    werewolfLeggings: {
        label: 'Werewolf Leggings',
        name: 'werewolfLeggings',
        type: 'leggings',
        set: 'werewolf',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 10,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    werewolfBoots: {
        label: 'Werewolf Boots',
        name: 'werewolfBoots',
        type: 'boots',
        set: 'werewolf',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 10,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Fishing Armors

    // Whitetip Shark Armor

    whitetipSharkHelmet: {
        label: 'Whitetip Shark Helmet',
        name: 'whitetipSharkHelmet',
        type: 'helmet',
        set: 'whitetipShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 1
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 3,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    whitetipSharkChestplate: {
        label: 'Whitetip Shark Chestplate',
        name: 'whitetipSharkChestplate',
        type: 'chestplate',
        set: 'whitetipShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 1
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 3,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    whitetipSharkLeggings: {
        label: 'Whitetip Shark Leggings',
        name: 'whitetipSharkLeggings',
        type: 'leggings',
        set: 'whitetipShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 1
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 3,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    whitetipSharkBoots: {
        label: 'Whitetip Shark Boots',
        name: 'whitetipSharkBoots',
        type: 'boots',
        set: 'whitetipShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 1
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 3,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Tiger Shark Armor

    tigerSharkHelmet: {
        label: 'Tiger Shark Helmet',
        name: 'tigerSharkHelmet',
        type: 'helmet',
        set: 'tigerShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 2
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 5,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    tigerSharkChestplate: {
        label: 'Tiger Shark Chestplate',
        name: 'tigerSharkChestplate',
        type: 'chestplate',
        set: 'tigerShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 2
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 5,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    tigerSharkLeggings: {
        label: 'Tiger Shark Leggings',
        name: 'tigerSharkLeggings',
        type: 'leggings',
        set: 'tigerShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 2
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 5,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    tigerSharkBoots: {
        label: 'Tiger Shark Boots',
        name: 'tigerSharkBoots',
        type: 'boots',
        set: 'tigerShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 2
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 5,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Great White Shark Armor

    greatWhiteSharkHelmet: {
        label: 'Great White Shark Helmet',
        name: 'greatWhiteSharkHelmet',
        type: 'helmet',
        set: 'greatWhiteShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 3
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 7,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    greatWhiteSharkChestplate: {
        label: 'Great White Shark Chestplate',
        name: 'greatWhiteSharkChestplate',
        type: 'chestplate',
        set: 'greatWhiteShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 3
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 7,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    greatWhiteSharkLeggings: {
        label: 'Great White Shark Leggings',
        name: 'greatWhiteSharkLeggings',
        type: 'leggings',
        set: 'greatWhiteShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 3
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 7,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    greatWhiteSharkBoots: {
        label: 'Great White Shark Boots',
        name: 'greatWhiteSharkBoots',
        type: 'boots',
        set: 'greatWhiteShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 3
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 7,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Megalodon Shark Armor

    megalodonSharkHelmet: {
        label: 'Megalodon Shark Helmet',
        name: 'megalodonSharkHelmet',
        type: 'helmet',
        set: 'megalodonShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 4
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 10,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    megalodonSharkChestplate: {
        label: 'Megalodon Shark Chestplate',
        name: 'megalodonSharkChestplate',
        type: 'chestplate',
        set: 'megalodonShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 4
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 10,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    megalodonSharkLeggings: {
        label: 'Megalodon Shark Leggings',
        name: 'megalodonSharkLeggings',
        type: 'leggings',
        set: 'megalodonShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 4
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 10,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    megalodonSharkBoots: {
        label: 'Megalodon Shark Boots',
        name: 'megalodonSharkBoots',
        type: 'boots',
        set: 'megalodonShark',
        fullsetEffect: {
            effect: 'skipFishingTier',
            tier: 4
        },
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 10,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Wands

    wandOfHealing: {
        label: 'Wand of Healing',
        name: 'wandOfHealing',
        type: 'wand',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 1,
        healing: 3,
        regeneration: 0,
    },

    wandOfMending: {
        label: 'Wand of Mending',
        name: 'wandOfMending',
        type: 'wand',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 1,
        healing: 5,
        regeneration: 0,
    },


    // Weapons

    bronzeSword: {
        label: 'Bronze Sword',
        name: 'bronzeSword',
        type: 'weapon',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 2,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    ironSword: {
        label: 'Iron Sword',
        name: 'ironSword',
        type: 'weapon',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 2,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    diamondSword: {
        label: 'Diamond Sword',
        name: 'diamondSword',
        type: 'weapon',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 2,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    sharpDiamondSword: {
        label: 'Sharp Diamond Sword',
        name: 'sharpDiamondSword',
        type: 'weapon',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 2,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    mithrilSword: {
        label: 'Mithril Sword',
        name: 'mithrilSword',
        type: 'weapon',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 2,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Pickaxes

    ironPickaxe: {
        label: 'Iron Pickaxe',
        name: 'ironPickaxe',
        type: 'tool',
        miningSpeedBonus: 0,
        miningLuckBonus: 1,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    goldPickaxe: {
        label: 'Gold Pickaxe',
        name: 'goldPickaxe',
        type: 'tool',
        miningSpeedBonus: 0,
        miningLuckBonus: 2,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    diamondPickaxe: {
        label: 'Diamond Pickaxe',
        name: 'diamondPickaxe',
        type: 'tool',
        miningSpeedBonus: 1,
        miningLuckBonus: 3,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    reinforcedDiamondPickaxe: {
        label: 'Reinforced Diamond Pickaxe',
        name: 'reinforcedDiamondPickaxe',
        type: 'tool',
        miningSpeedBonus: 1,
        miningLuckBonus: 5,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    mithrilPickaxe: {
        label: 'Mithril Pickaxe',
        name: 'mithrilPickaxe',
        type: 'tool',
        miningSpeedBonus: 2,
        miningLuckBonus: 7,
        fishingLuckBonus: 0,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    // Fishing Rods

    fishingRod: {
        label: 'Fishing Rod',
        name: 'fishingRod',
        type: 'rod',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 5,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    rodOfTheSea: {
        label: 'Rod of the Sea',
        name: 'rodOfTheSea',
        type: 'rod',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 15,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    luckyRod: {
        label: 'Lucky Rod',
        name: 'luckyRod',
        type: 'rod',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 30,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },

    blessedRod: {
        label: 'Blessed Rod',
        name: 'blessedRod',
        type: 'rod',
        miningSpeedBonus: 0,
        miningLuckBonus: 0,
        fishingLuckBonus: 50,
        healthBonus: 0,
        defenseBonus: 0,
        strengthBonus: 0,
        manaCost: 0,
        healing: 0,
        regeneration: 0,
    },
})